Models/ErrorViewModel.cs
using System;

namespace TreinaWeb.TestAspNetMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Person.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TreinaWeb.TestAspNetMvc.Models
{
    public class Person
    {
        [Required(ErrorMessage = "Please, type your name, is required.")]
        [DisplayName("Your name")]
        [MaxLength(50, ErrorMessage = "The name can only be 50 characters long")]
        [MinLength(4, ErrorMessage = "The name must be at least 4 characters")]
        public string Name { get; set; }

        [DisplayName("Your age")]
        public int Age { get; set; }

        [Required(ErrorMessage = "Please, type the city you live, is required.")]
        [DisplayName("The city you live")]
        [MaxLength(20, ErrorMessage = "The city name can only be 20 characters long")]
        [MinLength(4, ErrorMessage = "The city name must be at least 4 characters")]
        public string City { get; set; }

        [Required(ErrorMessage = "Please, I need your email, it's a surprise . ( ͡° ͜ʖ ͡°)")]
        [DisplayName("Your email")]
        [MaxLength(30, ErrorMessage = "Your email can only be 30 characters long")]
        [MinLength(8, ErrorMessage = "The name must be at least 8 characters")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [BindNever]
        public bool Active { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TreinaWeb.TestAspNetMvc.Models;

namespace TreinaWeb.TestAspNetMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TestController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StackExchange.Redis;
using TreinaWeb.TestAspNetMvc.Models;

namespace TreinaWeb.TestAspNetMvc.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Person person)
        {
            if (ModelState.IsValid)
            {
                person.Active = true;
                return View("Greetings", person);
            }
            else
                return View(person);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TreinaWeb.TestAspNetMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TreinaWeb.TestAspNetMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TreinaWeb.TestAspNetMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Test/Greetings.cshtml
@using TreinaWeb.TestAspNetMvc.Models
@model Person
<head>
    <link rel="stylesheet" href="~/css/greetings.css" />
</head>
@{
    ViewBag.Title = "Greetings";
}

<h2>Greetings</h2>

<p>Hello, welcome @Model.Name!</p>
@Html.LabelFor(p => p.Age) is @Model.Age years old, right?<br />
@Html.LabelFor(p => p.City) is @Model.City, cool!<br />
And I'll sent you to @Html.LabelFor(p => p.Email, new { @class = "lowercase" }) (this one: @Model.Email) pretty soon!

Views/Test/Index.cshtml
@page
@using TreinaWeb.TestAspNetMvc.Models
@model Person

@{
    ViewBag.Title = "Example";
}

<h2>Index</h2>
<br />
<br />
@using (Html.BeginForm("Index", "Test", FormMethod.Post))
{

    @Html.AntiForgeryToken()


    @Html.ValidationSummary(true)

    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2">
            @Html.LabelFor(p => p.Name)
        </div>
        <div class="col-sm-12 col-md-8 col-lg-6">
            @Html.EditorFor(p => p.Name, new { htmlAttributes = new { id = "txbName", @class = "form-control" } })
            @Html.ValidationMessageFor(p => p.Name)
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2">
            @Html.LabelFor(p => p.Age)
        </div>
        <div class="col-sm-12 col-md-8 col-lg-6">
            @Html.EditorFor(p => p.Age, new { htmlAttributes = new { id = "txbAge", @class = "form-control" } })
            @Html.ValidationMessageFor(p => p.Age)
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2">
    @Html.LabelFor(p => p.City)
</div>
        <div class="col-sm-12 col-md-8 col-lg-6">
            @Html.EditorFor(p => p.City, new { htmlAttributes = new { id = "txbCity", @class = "form-control" } })
            @Html.ValidationMessageFor(p => p.City)
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2">
            @Html.LabelFor(p => p.Email)
        </div>
        <div class="col-sm-12 col-md-8 col-lg-6">
            @Html.EditorFor(p => p.Email, new { htmlAttributes = new { id = "txbEmail", @class = "form-control" } })
            @Html.ValidationMessageFor(p => p.Email)
        </div>
    </div>

        <input type="submit" id="btnSubmit" value="Send" class="btn btn-primary"/>

        }